# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from coop_per_msgs/ObjectDetection.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class ObjectDetection(genpy.Message):
  _md5sum = "54af25369463fc072d402f549fb57e71"
  _type = "coop_per_msgs/ObjectDetection"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """#Position in Global Space
#Note that 32 bit floats have a worst case accuracy around ~1.7 meters
#While a 64 bit float has a worset case accuracy around ~3.16 nanometers
float64 latitude
float64 longitude
float64 altitude

#The objects dimensions in meters
float32 length
float32 width
float32 height

#The objects rotation along its up/down (Z) axis
float32 rotation

#The UNIX epoch timestamp
float64 timestamp

#The class name and its confidence score
string class
float32 confidence
"""
  __slots__ = ['latitude','longitude','altitude','length','width','height','rotation','timestamp','class_','confidence']
  _slot_types = ['float64','float64','float64','float32','float32','float32','float32','float64','string','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       latitude,longitude,altitude,length,width,height,rotation,timestamp,class_,confidence

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ObjectDetection, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.latitude is None:
        self.latitude = 0.
      if self.longitude is None:
        self.longitude = 0.
      if self.altitude is None:
        self.altitude = 0.
      if self.length is None:
        self.length = 0.
      if self.width is None:
        self.width = 0.
      if self.height is None:
        self.height = 0.
      if self.rotation is None:
        self.rotation = 0.
      if self.timestamp is None:
        self.timestamp = 0.
      if self.class_ is None:
        self.class_ = ''
      if self.confidence is None:
        self.confidence = 0.
    else:
      self.latitude = 0.
      self.longitude = 0.
      self.altitude = 0.
      self.length = 0.
      self.width = 0.
      self.height = 0.
      self.rotation = 0.
      self.timestamp = 0.
      self.class_ = ''
      self.confidence = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3d4fd().pack(_x.latitude, _x.longitude, _x.altitude, _x.length, _x.width, _x.height, _x.rotation, _x.timestamp))
      _x = self.class_
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.confidence
      buff.write(_get_struct_f().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 48
      (_x.latitude, _x.longitude, _x.altitude, _x.length, _x.width, _x.height, _x.rotation, _x.timestamp,) = _get_struct_3d4fd().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.class_ = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.class_ = str[start:end]
      start = end
      end += 4
      (self.confidence,) = _get_struct_f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3d4fd().pack(_x.latitude, _x.longitude, _x.altitude, _x.length, _x.width, _x.height, _x.rotation, _x.timestamp))
      _x = self.class_
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.confidence
      buff.write(_get_struct_f().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 48
      (_x.latitude, _x.longitude, _x.altitude, _x.length, _x.width, _x.height, _x.rotation, _x.timestamp,) = _get_struct_3d4fd().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.class_ = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.class_ = str[start:end]
      start = end
      end += 4
      (self.confidence,) = _get_struct_f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3d4fd = None
def _get_struct_3d4fd():
    global _struct_3d4fd
    if _struct_3d4fd is None:
        _struct_3d4fd = struct.Struct("<3d4fd")
    return _struct_3d4fd
_struct_f = None
def _get_struct_f():
    global _struct_f
    if _struct_f is None:
        _struct_f = struct.Struct("<f")
    return _struct_f
