// Generated by gencpp from file coop_per_msgs/ObjectDetection.msg
// DO NOT EDIT!


#ifndef COOP_PER_MSGS_MESSAGE_OBJECTDETECTION_H
#define COOP_PER_MSGS_MESSAGE_OBJECTDETECTION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace coop_per_msgs
{
template <class ContainerAllocator>
struct ObjectDetection_
{
  typedef ObjectDetection_<ContainerAllocator> Type;

  ObjectDetection_()
    : lat_y(0.0)
    , long_x(0.0)
    , altitude_z(0.0)
    , depth(0.0)
    , width(0.0)
    , height(0.0)
    , rotation(0.0)
    , class_name()
    , confidence(0.0)  {
    }
  ObjectDetection_(const ContainerAllocator& _alloc)
    : lat_y(0.0)
    , long_x(0.0)
    , altitude_z(0.0)
    , depth(0.0)
    , width(0.0)
    , height(0.0)
    , rotation(0.0)
    , class_name(_alloc)
    , confidence(0.0)  {
  (void)_alloc;
    }



   typedef double _lat_y_type;
  _lat_y_type lat_y;

   typedef double _long_x_type;
  _long_x_type long_x;

   typedef double _altitude_z_type;
  _altitude_z_type altitude_z;

   typedef float _depth_type;
  _depth_type depth;

   typedef float _width_type;
  _width_type width;

   typedef float _height_type;
  _height_type height;

   typedef float _rotation_type;
  _rotation_type rotation;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _class_name_type;
  _class_name_type class_name;

   typedef float _confidence_type;
  _confidence_type confidence;





  typedef boost::shared_ptr< ::coop_per_msgs::ObjectDetection_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::coop_per_msgs::ObjectDetection_<ContainerAllocator> const> ConstPtr;

}; // struct ObjectDetection_

typedef ::coop_per_msgs::ObjectDetection_<std::allocator<void> > ObjectDetection;

typedef boost::shared_ptr< ::coop_per_msgs::ObjectDetection > ObjectDetectionPtr;
typedef boost::shared_ptr< ::coop_per_msgs::ObjectDetection const> ObjectDetectionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::coop_per_msgs::ObjectDetection_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::coop_per_msgs::ObjectDetection_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::coop_per_msgs::ObjectDetection_<ContainerAllocator1> & lhs, const ::coop_per_msgs::ObjectDetection_<ContainerAllocator2> & rhs)
{
  return lhs.lat_y == rhs.lat_y &&
    lhs.long_x == rhs.long_x &&
    lhs.altitude_z == rhs.altitude_z &&
    lhs.depth == rhs.depth &&
    lhs.width == rhs.width &&
    lhs.height == rhs.height &&
    lhs.rotation == rhs.rotation &&
    lhs.class_name == rhs.class_name &&
    lhs.confidence == rhs.confidence;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::coop_per_msgs::ObjectDetection_<ContainerAllocator1> & lhs, const ::coop_per_msgs::ObjectDetection_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace coop_per_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::coop_per_msgs::ObjectDetection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::coop_per_msgs::ObjectDetection_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::coop_per_msgs::ObjectDetection_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::coop_per_msgs::ObjectDetection_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::coop_per_msgs::ObjectDetection_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::coop_per_msgs::ObjectDetection_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::coop_per_msgs::ObjectDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2b10fb12cf3dbf0187359d2e5baae524";
  }

  static const char* value(const ::coop_per_msgs::ObjectDetection_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2b10fb12cf3dbf01ULL;
  static const uint64_t static_value2 = 0x87359d2e5baae524ULL;
};

template<class ContainerAllocator>
struct DataType< ::coop_per_msgs::ObjectDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "coop_per_msgs/ObjectDetection";
  }

  static const char* value(const ::coop_per_msgs::ObjectDetection_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::coop_per_msgs::ObjectDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#Position in Global Space\n"
"#Note that 32 bit floats have a worst case accuracy around ~1.7 meters\n"
"#While a 64 bit float has a worset case accuracy around ~3.16 nanometers\n"
"float64 lat_y\n"
"float64 long_x\n"
"float64 altitude_z\n"
"\n"
"#The objects dimensions in meters\n"
"float32 depth\n"
"float32 width\n"
"float32 height\n"
"\n"
"#The objects rotation along its up/down (Z) axis\n"
"float32 rotation\n"
"\n"
"#The class name and its confidence score\n"
"string class_name\n"
"float32 confidence\n"
;
  }

  static const char* value(const ::coop_per_msgs::ObjectDetection_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::coop_per_msgs::ObjectDetection_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.lat_y);
      stream.next(m.long_x);
      stream.next(m.altitude_z);
      stream.next(m.depth);
      stream.next(m.width);
      stream.next(m.height);
      stream.next(m.rotation);
      stream.next(m.class_name);
      stream.next(m.confidence);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObjectDetection_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::coop_per_msgs::ObjectDetection_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::coop_per_msgs::ObjectDetection_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "lat_y: ";
    Printer<double>::stream(s, indent + "  ", v.lat_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "long_x: ";
    Printer<double>::stream(s, indent + "  ", v.long_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "altitude_z: ";
    Printer<double>::stream(s, indent + "  ", v.altitude_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "depth: ";
    Printer<float>::stream(s, indent + "  ", v.depth);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "width: ";
    Printer<float>::stream(s, indent + "  ", v.width);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "height: ";
    Printer<float>::stream(s, indent + "  ", v.height);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "rotation: ";
    Printer<float>::stream(s, indent + "  ", v.rotation);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "class_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.class_name);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "confidence: ";
    Printer<float>::stream(s, indent + "  ", v.confidence);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COOP_PER_MSGS_MESSAGE_OBJECTDETECTION_H
