// Generated by gencpp from file coop_per_msgs/ObjectDetection.msg
// DO NOT EDIT!


#ifndef COOP_PER_MSGS_MESSAGE_OBJECTDETECTION_H
#define COOP_PER_MSGS_MESSAGE_OBJECTDETECTION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace coop_per_msgs
{
template <class ContainerAllocator>
struct ObjectDetection_
{
  typedef ObjectDetection_<ContainerAllocator> Type;

  ObjectDetection_()
    : latitude(0.0)
    , longitude(0.0)
    , altitude(0.0)
    , length(0.0)
    , width(0.0)
    , height(0.0)
    , rotation(0.0)
    , timestamp(0.0)
    , class()
    , confidence(0.0)  {
    }
  ObjectDetection_(const ContainerAllocator& _alloc)
    : latitude(0.0)
    , longitude(0.0)
    , altitude(0.0)
    , length(0.0)
    , width(0.0)
    , height(0.0)
    , rotation(0.0)
    , timestamp(0.0)
    , class(_alloc)
    , confidence(0.0)  {
  (void)_alloc;
    }



   typedef double _latitude_type;
  _latitude_type latitude;

   typedef double _longitude_type;
  _longitude_type longitude;

   typedef double _altitude_type;
  _altitude_type altitude;

   typedef float _length_type;
  _length_type length;

   typedef float _width_type;
  _width_type width;

   typedef float _height_type;
  _height_type height;

   typedef float _rotation_type;
  _rotation_type rotation;

   typedef double _timestamp_type;
  _timestamp_type timestamp;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _class_type;
  _class_type class;

   typedef float _confidence_type;
  _confidence_type confidence;





  typedef boost::shared_ptr< ::coop_per_msgs::ObjectDetection_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::coop_per_msgs::ObjectDetection_<ContainerAllocator> const> ConstPtr;

}; // struct ObjectDetection_

typedef ::coop_per_msgs::ObjectDetection_<std::allocator<void> > ObjectDetection;

typedef boost::shared_ptr< ::coop_per_msgs::ObjectDetection > ObjectDetectionPtr;
typedef boost::shared_ptr< ::coop_per_msgs::ObjectDetection const> ObjectDetectionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::coop_per_msgs::ObjectDetection_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::coop_per_msgs::ObjectDetection_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::coop_per_msgs::ObjectDetection_<ContainerAllocator1> & lhs, const ::coop_per_msgs::ObjectDetection_<ContainerAllocator2> & rhs)
{
  return lhs.latitude == rhs.latitude &&
    lhs.longitude == rhs.longitude &&
    lhs.altitude == rhs.altitude &&
    lhs.length == rhs.length &&
    lhs.width == rhs.width &&
    lhs.height == rhs.height &&
    lhs.rotation == rhs.rotation &&
    lhs.timestamp == rhs.timestamp &&
    lhs.class == rhs.class &&
    lhs.confidence == rhs.confidence;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::coop_per_msgs::ObjectDetection_<ContainerAllocator1> & lhs, const ::coop_per_msgs::ObjectDetection_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace coop_per_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::coop_per_msgs::ObjectDetection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::coop_per_msgs::ObjectDetection_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::coop_per_msgs::ObjectDetection_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::coop_per_msgs::ObjectDetection_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::coop_per_msgs::ObjectDetection_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::coop_per_msgs::ObjectDetection_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::coop_per_msgs::ObjectDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "54af25369463fc072d402f549fb57e71";
  }

  static const char* value(const ::coop_per_msgs::ObjectDetection_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x54af25369463fc07ULL;
  static const uint64_t static_value2 = 0x2d402f549fb57e71ULL;
};

template<class ContainerAllocator>
struct DataType< ::coop_per_msgs::ObjectDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "coop_per_msgs/ObjectDetection";
  }

  static const char* value(const ::coop_per_msgs::ObjectDetection_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::coop_per_msgs::ObjectDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#Position in Global Space\n"
"#Note that 32 bit floats have a worst case accuracy around ~1.7 meters\n"
"#While a 64 bit float has a worset case accuracy around ~3.16 nanometers\n"
"float64 latitude\n"
"float64 longitude\n"
"float64 altitude\n"
"\n"
"#The objects dimensions in meters\n"
"float32 length\n"
"float32 width\n"
"float32 height\n"
"\n"
"#The objects rotation along its up/down (Z) axis\n"
"float32 rotation\n"
"\n"
"#The UNIX epoch timestamp\n"
"float64 timestamp\n"
"\n"
"#The class name and its confidence score\n"
"string class\n"
"float32 confidence\n"
;
  }

  static const char* value(const ::coop_per_msgs::ObjectDetection_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::coop_per_msgs::ObjectDetection_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.latitude);
      stream.next(m.longitude);
      stream.next(m.altitude);
      stream.next(m.length);
      stream.next(m.width);
      stream.next(m.height);
      stream.next(m.rotation);
      stream.next(m.timestamp);
      stream.next(m.class);
      stream.next(m.confidence);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObjectDetection_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::coop_per_msgs::ObjectDetection_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::coop_per_msgs::ObjectDetection_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "latitude: ";
    Printer<double>::stream(s, indent + "  ", v.latitude);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "longitude: ";
    Printer<double>::stream(s, indent + "  ", v.longitude);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "altitude: ";
    Printer<double>::stream(s, indent + "  ", v.altitude);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "length: ";
    Printer<float>::stream(s, indent + "  ", v.length);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "width: ";
    Printer<float>::stream(s, indent + "  ", v.width);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "height: ";
    Printer<float>::stream(s, indent + "  ", v.height);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "rotation: ";
    Printer<float>::stream(s, indent + "  ", v.rotation);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "timestamp: ";
    Printer<double>::stream(s, indent + "  ", v.timestamp);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "class: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.class);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "confidence: ";
    Printer<float>::stream(s, indent + "  ", v.confidence);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COOP_PER_MSGS_MESSAGE_OBJECTDETECTION_H
